//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public System.Guid IdDocumento { get; set; }
        public string Ruc { get; set; }
        public string Documento { get; set; }
        public string TipoDocumento { get; set; }
        public string Caja { get; set; }
        public Nullable<System.Guid> IdLocal { get; set; }
        public System.Guid IdTrama { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTimeOffset> FechaRegistroSet { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Documentos_Tramas Documentos_Tramas { get; set; }
    }
}
