//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos_Tramas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documentos_Tramas()
        {
            this.Documentos = new HashSet<Documentos>();
        }
    
        public System.Guid IdTrama { get; set; }
        public string json { get; set; }
        public string xml { get; set; }
        public string xmlzip { get; set; }
        public string Firmaxml { get; set; }
        public string Hash { get; set; }
        public string cdr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos> Documentos { get; set; }
    }
}
