//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public System.Guid IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTimeOffset> FechaRegistroSet { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<long> IdTipoUsuario { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
